// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsICp9ykoQaWNT3tShtsz53goGaF8D5o',
    appId: '1:1041289552556:android:4c171def4a8a5a92cdb509',
    messagingSenderId: '1041289552556',
    projectId: 'kindora-f3757',
    storageBucket: 'kindora-f3757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjuvR1mn8xBWYZmCaQqx83svfKHdzbIY',
    appId: '1:1041289552556:ios:5542cb42d0736d84cdb509',
    messagingSenderId: '1041289552556',
    projectId: 'kindora-f3757',
    storageBucket: 'kindora-f3757.firebasestorage.app',
    iosClientId: '1041289552556-13n6vlfedp4ofoaje0jgthh7qdrp90uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindora',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJZROgUqfPae9vz7_hWHvpxzVVToDnKIk',
    appId: '1:1041289552556:web:f4d01b45f7955100cdb509',
    messagingSenderId: '1041289552556',
    projectId: 'kindora-f3757',
    authDomain: 'kindora-f3757.firebaseapp.com',
    storageBucket: 'kindora-f3757.firebasestorage.app',
  );

}