-- 1. Create News Feed Table
CREATE TABLE IF NOT EXISTS public.kindora_news_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'ongoing'
);

-- 2. Create AI Recommendations Table
CREATE TABLE IF NOT EXISTS public.kindora_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    description TEXT,
    category TEXT,
    impact_score INT4 DEFAULT 95,
    match_reason TEXT,
    icon_name TEXT
);

-- 3. Security Policies (RLS)
ALTER TABLE public.kindora_news_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kindora_recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.kindora_news_updates FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read access" ON public.kindora_recommendations FOR SELECT TO public USING (true);